### ISSUE TITLE
consider moving from yarn to npm

### ISSUE THREAD

**Issue by kittaakos** [arduino/vscode-arduino-tools#20]
for the sake of simplicity, let's not force future contributors to use yarn

**Comment by Alexander-Taran** [comment]
@kittaakos is there a long read on the topic of why `Theia` is so tied to `yarn`?

**Comment by kittaakos** [comment]
Let's stick to `yarn`

**Comment by dankeboy36** [comment]
> [Theia does not work without `yarn`](https://github.com/eclipse-theia/theia/issues/775).

Theia devs plan to move to npm: https://github.com/eclipse-theia/theia/pull/14481.

Please consider reopening this issue.
