### ISSUE TITLE
Clone the GitHub Security settings of the `arduino/arduino-ide` project

### ISSUE THREAD

**Issue by kittaakos** [arduino/vscode-arduino-tools#42]
@rhpco, could you please help to configure the GH security of the project the same was as is in https://github.com/arduino/arduino-ide? We would like the followings to be enabled:

 - [ ] Security policy
 - [ ] Security advisories
 - [ ] Dependabot alerts (report the alerts but do not create the auto PRs if possible)
 - [ ] Code scanning alerts
 - [ ] Secret scanning alerts

Thank you!

**Comment by rhpco** [comment]
Done!

**Comment by kittaakos** [comment]
Thank you!
